name: Cowsay Alpine version

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./oreally_using_docker/cowsay/alpine --file ./oreally_using_docker/cowsay/alpine/Dockerfile --tag hhuntercu/devops_training:cowsay-alpine-$(date +%s)
